### ISSUE TITLE
Filled out fields unable to be edited

### ISSUE THREAD

**Issue by perkynades** [navikt/innbyggerpanelet#82]
Some fields with pre-defined values, such as editing a criteria or editing an insight project, is not possible. Trying to change the value of the input does nothing

**Comment by amundlrohne** [comment]
This isn't implemented yet.

**Comment by amundlrohne** [comment]
Criteria editing should be fixed with #99, still needs solution for insights

**Comment by amundlrohne** [comment]
This issue is not complete or representative of the current build.
